services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: coursedb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  api:
    build: ./api
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db/coursedb
    ports:
      - "8080:8080"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api

volumes:
  postgres_data:
